### ISSUE TITLE
As an Open Data Hub maintainer, I would like to split our kubernetes services into well defined namespaces

### ISSUE THREAD

**Issue by clezag** [noi-techpark/odh-infrastructure-v2#13]
Seeing as the deployments are now increasing in time, we should find a layout on how to split services into namespaces.
Something along the lines of:

- core (rabbitmq, writer route, notifier, mongo, mosquitto, camelk stuff)
- collectors
- transformers
- elaborations
- odh-core (outbound APIs, writer)

Maybe also less fine grained like
 - core  (core system)
 - data collectors (collectors, transformers, elaborations)

**Comment by sseppi** [comment]
This issue is related to the issue #16

**Comment by clezag** [comment]
Split is done into namespaces "core" and "collector". collector has both the data collectors and transformers.
