### ISSUE TITLE
MongoDB deployed as replica set

### ISSUE THREAD

**Issue by Luscha** [noi-techpark/odh-infrastructure-v2#43]
As an Open Data Hub maintainer i want MongoDB to be deployed as replica set and replicated on all availability zones

**Comment by clezag** [comment]
Note that currently we're limited to one availability zone only (issue with volume mounts across AZs), so this will go beyond only configuring MongoDB

**Comment by clezag** [comment]
All database connection strings have now been migrated to the mongodb+srv connection string style that better supports clustering. The connection string is retrieved from a central secret.

**Comment by christian-roggia** [comment]
Is there anything else needed here? This seems to be properly configured with `replicaset` mode set to true for the Helm chart and the `ReplicaSetKey` defined during deplyoments.

**Comment by clezag** [comment]
The main remaining issue is probably that we currently run in a single subnet and AZ only because of the restrictions with mounting PVs across AZs.

**Comment by christian-roggia** [comment]
I will work on support for multi-AZ then.
